### ISSUE TITLE
Missing graphs in Understanding Memoization

### ISSUE THREAD

**Issue by bgins** [elemaudio/docs#1]
Hey there :wave:

While reading the Understanding Memoization section, I noticed a couple of missing graphs:

https://github.com/elemaudio/docs/blob/27934c041066328214211321b35ed6b7f2f828e7/docs/guides/Understanding_Memoization.md?plain=1#L15

https://github.com/elemaudio/docs/blob/27934c041066328214211321b35ed6b7f2f828e7/docs/guides/Understanding_Memoization.md?plain=1#L25

**Comment by nick-thompson** [comment]
Hah, thanks @bgins good catch :) Fixed in 5e17ba27b0a2737eab83ff89f68b23fbd83842c2
